import { createSlice } from "@reduxjs/toolkit";

const userSlice = createSlice({
  name: "session",
  initialState: {
    token: null,
    user: null,
    summary: null,
    translation: {
      HOMEPAGE: {
        continuetitle:
          "Continue to exist on the internet for many further generations. Don’t be forgotten.",
        continuefirstbullet:
          "Be remembered by your children, grandchildren, great-grandchildren and far beyond!",
        continuesectondbullet: "Enable generations in the distant future to get to know you!",
        continuethirdbullet:
          "Remember and commemorate your lost family members, friends and acquaintances",
        story: "The story of your life",
        storydescription:
          "You can capture your life at The Afternet with stories, pictures and movies. You can share whatever you like, experiences, funny stories, special occasions and happenings, emotional things, certain wisdom etc.. With this, you determine how future generations will get to know you, not just as a name in a family tree, but as the real person you are! This enables you to continue to exist until the end of times!",
        network: "Network and curate",
        networkdescription:
          "You can invite family, friends and acquaintances to connect with you on The Afternet. One or more persons can be appointed as curator of your account and can push the button when required. With this your network will be informed about your death and your life story will become available online.",
        wishes: "Your wishes, physical and virtual",
        wishesdescription:
          "When the time comes, your curators can read your wishes, both physical (funeral, place, music, ceremony, message(s) that you want to communicate, availability of a last will and/or funeral insurance, guestlist etc.) and virtual (how long do you want to exist on The Afternet, what you want to happen with your social media accounts like Facebook and Instagram or with your cloud account and (mobile) devices where important pictures and movies can be found).",
        memories: "Share memories",
        memoriesdescription:
          "As soon as your life description is online, people within your network can enjoy your life timeline and stories. Further, they can add and share stories, pictures and movies to your life timeline, enabling the people within your network to remember you together.",
        remember: "Remember and honor your deceased family members, friends and acquaintances",
        rememberdescription:
          "During your life you can remember and honor deceased family members, friends and acquaintances at The Afternet and you can enjoy memories of other people that are placed on the life timeline of these deceased persons. This way, these persons remain part of your life and memories are kept alive.",
        create: "Create a new account",
        createdescription:
          "The Afternet offers you the possibility to create a lifelong free account.",
        signup: "Signup",
      },
      MENU: {
        home: "Home",
        network: "Network",
        profile: "Profile",
        manage: "Manage",
        inbox: "Inbox",
      },
      FOOTER: {
        privacy: "Privacy",
        terms: "Terms conditions",
        language: "Language",
        logout: "Logout",
        faq: "FAQ",
      },
      DASHBOARD: {
        updates: "Updates from your network",
        noupdates: "No updates were found",
        moreupdates: "Show more updates",
        yourafternet: "Your Afternet",
        editprofile: "Edit my profile",
        registerprofile: "Create profile for loved one",
        added: "added",
        memory: "memory",
        memories: "memories",
        curator: "curator",
        curators: "curators",
        appointed: "appointed",
        no: "No",
        wishesregistered: "registered",
        nowishes: "No wishes",
        allwishes: "All wishes",
        somewishes: "Several wishes",
        suggestions: "People you may know",
        manage: "Manage",
        norequests: "No requests",
        request: "request",
        requests: "requests",
        share: "Share",
        invite: "Invite your friends",
      },
      UPDATES: {
        memorycreated: "A memory has been added by",
        viewmemory: "View the memory",
        viewprofile: "View the life of",
        addmemory: "Add your memory",
        birthday: "has become {{ years }} years old",
        birthanniversary: "would have turned {{ years }} years old",
        deathanniversary: "has passed away {{ years }} years ago",
        memorycommentadded: "added a comment to the following memory",
        memoryliked: "likes the following memory",
      },
      NETWORK: {
        your: "Your network",
        someoneelse: "Network from {{ name }}",
        search: "Search for a profile",
        invited: "Friendship request sent",
        invitedmessage: "You have invited {{name}} to be added to your network",
        empty: "Your network is still empty",
        emptymessage:
          "Search above for friends, family and acquaintances to add them to your network",
      },
      MANAGEMENT: {
        nocurator: "You are not a curator yet",
        nocuratorinfo:
          "People from your network can ask you to become the curator of their profile. This means that you will manage the profile after the person dies.",
        create: "Create a",
        profile: "profile",
        createprofileinfo:
          "for a deceased person. You then become a curator and manage the profile",
        managedpersons: "Managed persons",
        reportdeath: "Report passed away",
        rememberperson: "Do you want to remember a deceased person?",
        rememberpersoninfo:
          "Create a profile for a deceased person. You then become a curator and manage the profile",
        rememberpersoncreate: "Create profile",
        friendshiprequests: "Friend requests",
        nofriendshiprequests: "There are no new friend requests for your managed people",
        incomingfriendrequest: "would like to be included in the network of",
        recentmemoires: "Last memories",
        norecentmemoires: "There are no memories added yet for your managed people",
        memoryinfo: "has added a memory to the timeline of",
        viewmemory: "View memory",
        nowpublic:
          "{{ name }}'s profile is now public. Condolence on behalf of everyone at The Afternet!",
        addedto: "{{ friend }} has been added to the network of {{ name }}",
        denyrequest: "Are you sure you want to decline {{name}} on {{friend}}'s' network?",
        denyrequestconfirmed: "{{name}} has not been added to the {{friend}} network",
        warning: "Pay attention!",
        warninginfo:
          "You are about to declare {{name}} dead. At that time, the profile is opened to everyone in the network. This process is irreversible. ",
        deathmessage: "Message (will be in the update)",
        deathmessageerror: "Enter a message",
        deathdate: "Date of death",
      },
      INBOX: {
        title: "Inbox",
        empty: "Your inbox is empty",
        emptyinfo: "You don't have any incoming friend or curator requests",
        friendshiprequest: "Friendship request",
        friendshipinvite: "would like to be join your network",
        curatorship: "Curatorship",
        curatorshipinvite: "would like to invite you as a curator",
        newfriend: "New Friend",
        newcurator: "New curator",
        acceptedrequest: "has accepted your request",
        friendconfirmed: "{{name}} has been added to your network",
        denyfriend: "Are you sure you want to decline {{name}} on your network?",
        denyfriendconfirmed: "{{name}} has not been added to your network",
        curatorconfirmed: "You are now a curator of {{name}}",
        denycurator: "Are you sure you don't want to be a curator about {{name}}'s profile?",
        denycuratorconfirmed: "Curator request of {{ name }} denied",
      },
      PROFILE: {
        EDIT: {
          timeline: "Timeline",
          data: "Info",
          curators: "Curators",
          wishes: "Wishes",
          network: "Network",
          settings: "Afternet settings",
          yourprofile: "Your profile",
          viewprofile: "View profile",
          newprofile: "New profile",
          addownmemory: "Add your memory",
          addmemory: "Add memory",
          basicinformation: "Base info",
          name: "Name",
          namerequired: "Please enter a name for this profile.",
          photo: "Profile picture",
          photorequired: "Please choose a photo for this profile.",
          headerimage: "Header picture",
          birthdate: "Date of birth",
          birthdaterequired: "Enter a date of birth",
          deathdate: "Date of death",
          motto: "Motto",
          biography: "Biography",
          locations: "Places",
          birthplace: "Place of birth",
          birthplacerequired: "Please enter a place of birth",
          lastresidence: "Places of residence",
          lastresidencerequired: "Please enter a city",
          restingplace: "Final resting place",
          lastrestingplace: "Last resting place",
          household: "Family",
          relations: "Relations",
          newrelation: "New relation",
          workandeducation: "Work and education",
          work: "Work",
          education: "Education",
          sparetime: "Freetime",
          hobbies: "Hobbies",
          holidays: "Travels",
          yourcurators: "Your curators",
          curatorsof: "Curators of {{ name }}",
          curatorinfo:
            "Curators manage your profile after your death and can push that button when required. It is best to appoint more than one.",
          curatorinvited: "Curatorship request send",
          curatorinvitedinfo: "You have invited {{name}} to become a curator for you",
          curatorinvitedinfofriend: "You have invited {{name}} to become the curator of {{friend}}",
          wishesdeathmessage: "Message when passed away",
          wishesdeathmessageinfo:
            "Type here the message that you want to have sent in your name immediately after notification of death to all your friends on The Afternet",
          wishesonline: "Wishes social media / data",
          wishesonlineinfo:
            "Give information on what you want to happen with your social media accounts like Facebook and Instagram or with your cloud accounts and (mobile) devices where important pictures and movies can be found. If desired, provide information here on your userID’s / passwords to your curators",
          wishesfuneral: "Wishes for your funeral",
          wishesfuneralinfo:
            " How would you like to have your funeral, where, in what way, guestlist, unwanted guests, certain messages etc.",
          wishesmusic: "Music at your funeral",
          wishesmusicinfo: "Provide information here on the music you want at your funeral",
          wishestestament: "Information last will and notary",
          wishestestamentinfo: "Do you have a last will and if so, which notary?",
          wishesinsurance: "Information on funeral insurance",
          wishesinsuranceinfo:
            "Do you have a funeral insurance and if so, which insurance company / policy number?",
          wishesinformation: "Other information for your curators",
          wishesinformationinfo:
            "Give additional information, wishes, messages to your curators here",
          networkof: "Network of {{ name }}",
          addfriends: "Add friends",
          friendrequestsent: "Friend request sent",
          friendrequestsentinfo: "You have invited {{friend}} to be added to the {{name}} network",
          emptynetwork: "The network of {{ name }} is still empty",
          emptynetworkinfo:
            "Search above for friends, family and acquaintances to add them to the network of {{name}}",
          available: "Period online after death",
          availableinfo:
            "An account at The Afternet is free of charge during your entire life. As an introduction your life story and timeline will remain online for one year after your death. With the select option below it's possible to extend this time.",
          profilewhenalive: "Profile when alive",
          profilewhenpassedaway: "Profile after death",
          publiclabel: "Public profile",
          public: "Public",
          publicinfowhenalive:
            "All data (excluding the information for your curators) will be visible and findable for people within and outside your network.",
          publicinfo:
            "All data (excluding the information for your curators) will be visible and findable after you passed away for people within and outside your network.",
          private: "Private",
          privateinfowhenalive:
            "Only persons within your network can view all your information (except information for your curators). Persons outside your network can only see your base information (profile picture, name, date of birth, place of birth and residences) after your death.",
          privateinfo:
            "Only persons within your network can view all your information (except information for your curators) after your death. Persons outside your network can only see your base information (profile picture, name, date of birth, place of birth and residences) after your death.",
          memorycreation: "Who can add memories",
          memorycreationerror:
            "This option is only possible if your 'Profile after death' is set to 'Public profile'",
          settings: "Settings",
          chosenlanguage: "Chosen language",
          addnewcurator: "Add new curator",
          removecurator: "Remove",
          email: "E-mail",
          emailrequired: "Please enter an e-mail",
          emailchanged: "Your e-mail has been changed, we have send you an e-mail",
          EXPIRATIONS: {
            oneyear: "1 year",
            fiveyear: "5 years",
            tenyear: "10 years",
            twentyfiveyear: "25 years",
            fiftyyear: "50 years",
            seventyfiveyear: "75 years",
            hundredyear: "100 years",
            twohundredyear: "200 years",
            year: "year",
          },
        },
        VIEW: {
          year: "year",
          add: "Add {{name}} to your network",
          flowers: "Flowers for",
          given: "This flower was given by",
          addfirstflower: "Give flowers too",
          addflower: "Give flowers",
          about: "About {{ name }}",
          summary: "Summary",
          birthplace: "Bron",
          lastresidence: "Residence",
          restingplace: "Restingplace",
          partner: "Partner",
          father: "Father",
          mother: "Mother",
          stepfather: "Step or adoption father",
          stepmother: "Step or adoption mother",
          children: "Children",
          grandfather: "Grandfather",
          grandmother: "Grandmother",
          work: "Work",
          education: "education",
          hobbies: "Hobbies",
          holidays: "Travels",
          viewnetwork: "View network",
          addtonetwork: "Add {{name}} to your network",
          addmemoire: "Add memory",
          addownmemoire: "Add your own memory",
          interestedintimeline: "Curious about the life story of",
          timelineof: "Life story of",
          timelineofdescription:
            "Below you will find the memories of {{name}}. Written by family, friends, acquaintances and you!",
          pedigree: "Partial family tree",
        },
      },
      COOKIEBAR: {
        title: "Hey! The Afternet uses cookies",
        description: "We use cookies to improve your experience with The Afternet.",
        descriptionline1: "Do you not feel like getting cookies? Then close this message.",
        descriptionline2: "You can also decide later to accept Cookies.",
        accept: "Accept",
        deny: "No please",
      },
      WIZARD: {
        title: "Welcome to The Afternet",
        description: "Before you can continue, we need some basic information:",
        formtitle: "Basic information",
        name: "Name",
        nameerror: "Please enter a name for this profile.",
        email: "E-mail",
        emailerror: "Enter an email address",
        password: "Password",
        passworderror: "Fill in a password",
        passworderrorlength: "A password must be at least 8 characters long",
        confirmpassword: "Confirm Password",
        confirmpassworderror: "Fill in a password",
        confirmpassworderrorlength: "A password must be at least 8 characters long",
        confirmpassworderrormatch: "The passwords do not match",
        birthdate: "Date of birth",
        birthdateinformation: "We need your date of birth for optimal functioning of The Afternet.",
        profilepicture: "Profile picture",
        birthplace: "Place of birth",
        birthplaceerror: "Enter a place of birth",
        lastresidence: "Residence",
        lastresidenceerror: "Enter a city",
        editinformation:
          "Do you want to further personalize your profile or change your basic data at a later time? The settings can be found under the 'profile' menu and the 'Info' tab.",
        THANKS: {
          title: "Thanks!",
          emailinformation:
            "An email with an activation link has just been sent to the email address you provide. To log in to The Afternet you will first have to activate your account by clicking on this link.",
          personalinfo: "You have just entered the necessary information for using The Afternet.",
          invitefriends:
            "Also invite your friends and family to The Afternet with the text below *",
          quote:
            "I created an account on The Afternet and would love it if you also create an account there and connect with me.",
          share: "Share",
          dashboard: "Visit the dashboard",
          recentlylosesomeone:
            "Recently lost a loved one and do you want to give him or her a place for all your memories?",
          createprofileinformation:
            "Then create a profile for him or her and start, together with other relatives, filling his or her lifeline with all the wonderful memories you have shared with each other!",
          createprofile: "Create a profile",
          editprofilemessage: "You can change your profile via the 'profile' option in the menu",
        },
      },
      RESET: {
        newpassword: "New password",
        password: "password",
        enterpassword: "Fill in a password",
        minimumpasswordlength: "A password must be at least 8 characters long",
        confirmpassword: "Confirm new password",
        passwordmatch: "The passwords do not match",
      },
      LOGIN: {
        title: "Login to The Afternet",
        email: "E-mail",
        emailerror: "Please enter an e-mail",
        password: "Password",
        passwordrequired: "Please enter a password.",
        passwordforgotten: "Forgot your password",
        login: "Login",
        or: "or",
        createaccount: "Create an account",
        facebook: "with Facebook",
        notactivated:
          "The specified account has not yet been activated, a new activation e-mail has been sent",
        emailsent: "An email has been sent to the specified e-mail",
        notfound: "The provided e-mail was not found",
      },
      CONSTANT: {
        MEMORYCREATION: {
          curators: "Only curators",
          friends: "Friends and curators",
          everyone: "Anyone",
        },
        RELATIONSTYPES: {
          partner: "Partner",
          father: "Father",
          mother: "Mother",
          stepfather: "Step or adoption father",
          stepmother: "Step or adoption mother",
          children: "Children",
          grandfather: "Grandfather",
          grandmother: "Grandmother",
        },
      },
      SAVING: {
        generic: "The changes are saved",
      },
      ERRORS: {
        curatorself: "You cannot register yourself as a curator.",
        curatorexisting: "have you already added.",
        curatorinvited: "have you already invited as a curator.",
        curatordeceased:
          "unfortunately passed away, and therefore cannot become a curator for you.",
        curatorother: "cannot be specified as a curator.",
        networksent: "Your request to {{name}} has been sent",
        networkself: "You cannot add yourself to your network",
        networkexisting: "You have already added {{name}} to your network",
        networkinvited: "You have already sent {{name}} a friend request",
        networkother: "{{name}} cannot be added to your network",
        networkremove: "Are you sure you want to remove {{name}} from your network?",
        networkremovesuccess: "{{name}} has been removed from your network",
        genericerror: "Something went wrong, please try again later",
        alreadyexists: "An account with the chosen email address already exists",
        createprofile: "Something went wrong while registering the profile",
        profileimagesize:
          "The profile picture could not be saved because the file is too large. Try a smaller file",
        genericprofileerror: "The profile could not be saved, please try again later",
        removerelation: "Something went wrong while deleting the relationship",
        updaterelation: "Something went wrong while updating the relationship",
        addrelation: "Something went wrong while creating the relationship",
        musthavecurator:
          "A profile must always contain a curator, invite someone else before you remove yourself",
        removeyourselfascurator: "Are you sure you no longer want to be a curator of",
        onlyremoveyourself: "As a curator you can only remove yourself",
        curatorareyousure: "Are your sure that you want to remove",
        curatorremovefromprofile: "{{name}} as curator of your profile?",
        friendareyousure: "Are you sure you want to add",
        friendaddto: "to the network of",
        friendadd: "to your network",
        errorsaving: "Something went wrong while saving",
        imageerror: "Something went wrong while saving the image: {{image}}",
      },
      DATEDROPDOWNS: {
        day: "day",
        month: "month",
        months: "months",
        year: "year",
        pastdate: "Enter a date from the past",
        minage: "The chosen age must be at least {{ year }} years old",
        validate:
          "Please enter a valid date for your memory, but you may leave the day and / or month empty.",
      },
      TIMELINE: {
        about: "About",
        like: "like",
        writecomment: "Write a comment ...",
        memoirecreated: "The memory is {{status}} the timeline of {{name}}",
        memoirechanged: "changed to",
        memoireadded: "added to",
        memoireremove:
          "Are you sure you want to delete this memory from your timeline? This cannot be undone.",
        memoireremovefrom:
          "Are you sure you want to delete this memory from the {{name}} timeline? This cannot be undone.",
        memoireremovedconfirmed: "The memory has been deleted",
        editmemoiretitle: "Change memory",
        creatememoiretitle: "Add memory",
        memoiretitle: "Title",
        memoiretitlerequired: "Please enter a title for your memory",
        memoiredate: "Date",
        memoiredateinformation: "This does not have to be very specific",
        memoireoptional: "Optional",
        memoireto: "Your memory of {{name}}",
        memoirepicturesorvideo: "Photo's or video",
        memoirepictureiosnotice: "Please do not change the resolution",
        memoirepictureserror: "Photos may not be larger than 20MB.",
        memoireselectfocal: "Select a focus point:",
        memoireaddpicturedescription: "Description",
        memoireaddpicturedescriptioninfo: "Here you can add a description for this photo",
        memoirevideourl: "Video URL",
        memoirevideosinfo: "Youtube or Vimeo Video-url",
        and: "and",
        others: "others",
        likethismultiple: "like this",
        likethissingle: "likes this",
        videouploaded: "The video is uploading. This might take several minutes",
        VISIBILITY: {
          manage: "Manage visibility:",
          managealive: "Visible when alive:",
          managedead: "Visible when dead:",
          profile: "Conform Profile:",
          custom: "Custom:",
          nobody: "Nobody",
          friends: "Friends",
          public: "Public",
        },
      },
      SUCCESS: {
        profilesaved: "Profile saved successfully",
        passwordchanged: "Your password has been changed",
        wishessaved: "Wishes saved successfully",
      },
      GLOBAL: {
        accept: "Accept",
        deny: "Refuse",
        save: "Save",
        saving: "Saving ⏳",
        saved: "Saved ✓",
        edit: "Edit",
        lookup: "Search a profile",
        remove: "Remove",
        add: "Add",
        change: "Change",
        confirm: "Confirm",
        cancel: "Cancel",
      },
      FLOWERS: {
        flowers: "Flowers for {{ name }}",
        flowertype: "What kind of flowers do you want to give?",
        thanks: "Thank you for your flowers",
        unavailable: "Unfortunately you cannot give flowers to this person now ",
        givenby: "This flower was given by {{name}}",
        floweramount: "How long do you want the flower to be visible?",
        error: "No flower has been selected",
      },
      PAYMENT: {
        total: "Total",
        checkout: "Checkout",
      },
    },
  },

  reducers: {
    setToken: (state, action) => {
      state.token = action.payload;
    },

    logout: (state) => {
      state.token = null;
      state.user = null;
      state.summary = null;
    },

    setUser: (state, action) => {
      state.user = action.payload;
    },

    setSummary: (state, action) => {
      state.summary = action.payload;
    },

    setTranslation: (state, action) => {
      state.translation = action.payload;
    },
  },
});

export const { setToken, logout, setUser, setSummary, setTranslation } = userSlice.actions;
export default userSlice.reducer;
